ignore:
  - "KinSampleApp"
  - "KinBase/KinBase/Src/KinBackupRestoreModule"
  - "KinBase/KinBase/Src/Vendor/gen"
  - "KinBase/KinBase/Src/Storage/Gen"
  - "KinBase/KinBase/Src/Tools/ListObservable.swift"
  - "KinBase/KinBase/Src/Stellar/StellarSdkProxy.swift"
