coverage_service: cobertura_xml
xcodeproj: KinBase/KinBase.xcodeproj
workspace: ./kin-ios.xcworkspace
scheme: "KinBase"
source_directory: KinBase/KinBase
output_directory: coverage/
ignore:
  - Pods/*
  - KinGrpcApi/*
  - KinSampleApp/*
  - KinBase/KinBase/Classes/Grpc/*
  - KinBase/KinBase/Src/Vendor/gen/*
  - KinBase/KinBase/Src/Storage/Gen/*
  - KinBase/KinBase/Src/Tools/ListObservable.swift
  - KinBase/KinBase/Src/KinBackupRestoreModule/*
  - KinBase/KinBase/Src/Stellar/StellarSdkProxy.swift
