# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KinBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KinBase

    pod 'PromisesSwift', '~> 1.2.8'
    pod '!ProtoCompiler-gRPCPlugin', '~> 1.28.0'
    pod 'Protobuf', '~> 3.11.4'
    pod 'gRPC-ProtoRPC', '~> 1.28.0'

  target 'KinBaseTests' do
    # Pods for testing
    inherit! :search_paths
    
    pod 'PromisesSwift', '~> 1.2.8'
    pod '!ProtoCompiler-gRPCPlugin', '~> 1.28.0'
    pod 'Protobuf', '~> 3.11.4'
    pod 'gRPC-ProtoRPC', '~> 1.28.0'
  end

end

target 'KinBaseTestsHost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KinBaseTestsHost

end
